### ISSUE TITLE
deepin 官方有 9.1.8 的 QQ 了

### ISSUE THREAD

**Issue by bigshans** [countstarlight/deepin-wine-qq-arch#10]
尝试直接用 deepin 的，发现运行流畅，然而还有一些细节有问题。可以尝试打包用新版的。

**Comment by countstarlight** [comment]
感谢提醒，已更新并使用deepin官方原版：https://github.com/countstarlight/deepin-wine-qq-arch/commit/0c625c793f2c2a4c59eca632141059fb943b2054
