### ISSUE TITLE
调整窗口大小会导致界面控件消失

### ISSUE THREAD

**Issue by codexvn** [countstarlight/deepin-wine-qq-arch#11]
在调整窗口大小之后界面控件会有部分消失，另外窗口控件的位置也有错乱
![2019-12-06_21-00](https://user-images.githubusercontent.com/24852067/70324881-9cd51900-186b-11ea-94f4-243a975c0682.png)

**Comment by countstarlight** [comment]
测试在 `wine` 5.8 和 `deepin-wine` 2.18_22-3 上都不会出现这个问题
