### ISSUE TITLE
在输入框中无法输入中文，输入英文可以，另外图片无法加载。

### ISSUE THREAD

**Issue by Snopylz** [countstarlight/deepin-wine-qq-arch#13]
archlinux，使用fcitx，尝试在run.sh 前添加fcitx的设置没有效果。和系统语言设置有关吗？

**Comment by countstarlight** [comment]
输入法问题参照 https://github.com/countstarlight/deepin-wine-tim-arch/issues/5 试试

**Comment by Snopylz** [comment]
我把系统换成了中文环境，只在environment中添加好像没效果，在run.sh 中也加了
env locale=zh_CN
export XIM="fcitx"
export XMODIFIERS="@im=fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
重启后可以输入中文。
关于图片转圈参考了 https://blog.csdn.net/u013591740/article/details/104384534
update-grub 实际就是 grub-mkconfig -o /boot/grub/grub.cfg。
重启后可以加载出图片。。。目前不清楚这个禁用后会有什么后果。
以上均为在Tim上的尝试，QQ卸载了。

**Comment by Windforce17** [comment]
> 我把系统换成了中文环境，只在environment中添加好像没效果，在run.sh 中也加了
> env locale=zh_CN
> export XIM="fcitx"
> export XMODIFIERS="@im=fcitx"
> export GTK_IM_MODULE="fcitx"
> export QT_IM_MODULE="fcitx"
> 重启后可以输入中文。
> 关于图片转圈参考了 https://blog.csdn.net/u013591740/article/details/104384534
> update-grub 实际就是 grub-mkconfig -o /boot/grub/grub.cfg。
> 重启后可以加载出图片。。。目前不清楚这个禁用后会有什么后果。
> 以上均为在Tim上的尝试，QQ卸载了。

目前还是有图片无法加载问题，wine和arch kernel的ipv6不兼容，但新版的arch已经不能在内核禁用ipv6了。参见wiki中在/etc/sysctl.d/中将ipv6禁用的方法。禁用后无法使用ipv6
