### ISSUE TITLE
请更换PKGBUILD中的md5

### ISSUE THREAD

**Issue by skykeyjoker** [countstarlight/deepin-wine-qq-arch#14]
现在安装脚本从QQ官方地址下载下来的QQ EXE安装文件已经新于打包时的文件，因此yay安装时会提醒md5验证无法通过。请求更换PKGBUILD中的md5。

**Comment by countstarlight** [comment]
感谢提醒，已更新：https://github.com/countstarlight/deepin-wine-qq-arch/commit/a0543b46f668865d54f4312ec77e1017b901d169
