### ISSUE TITLE
文字缺失

### ISSUE THREAD

**Issue by JeroGC** [countstarlight/deepin-wine-qq-arch#15]
首次启动安装时有字显示
但登录界面没有显示任何文字
桌面环境是`Manjaro KDE 20.03`
`ReadMe`的更改deepin-wine都照做了，还是没有效果。

**Comment by AshleyCry** [comment]
老哥有解决方案了吗，我看了所有的issues也没找到解决方法

**Comment by kingcanfish** [comment]
+1

**Comment by JeroGC** [comment]
楼主目前改用`archlinux`了 ，楼上的各位不如尝试一下aur仓库中的`com.qq.tim.spark` ，亲测可以正常使用。
