### ISSUE TITLE
Deepin-wine更新后QQ卡死，字体缺失

### ISSUE THREAD

**Issue by paladin4fan** [countstarlight/deepin-wine-qq-arch#16]
Manjaro 20.0.3 KDE桌面环境
在此之前使用还算正常 除了点开QQ空间好友动态会crash之外聊天等功能都是正常的
pacman全面升级的时候更新了Deepin-Wine
在此之后QQ可以正常启动，但是打开聊天窗口时会卡住很久
如果聊天对象的昵称/备注是中文 聊天窗口顶部的名字会字体缺失变成黑框 并且聊天窗口直接卡死 无法输入文字和关闭 （托盘右键可退出QQ

**Comment by countstarlight** [comment]
`v9.4.2.27658-1` 已经修复了这个问题，建议参照 [自动切换](https://github.com/countstarlight/deepin-wine-qq-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90) 切换到 `deepin-wine`
