### ISSUE TITLE
在kde桌面环境下鼠标放在状态栏上不能查看消息

### ISSUE THREAD

**Issue by cheng-shuai** [countstarlight/deepin-wine-qq-arch#17]

**Comment by cheng-shuai** [comment]
切换为deepin-wine还是不行

**Comment by taotieren** [comment]
已修复 
https://github.com/countstarlight/deepin-wine-qq-arch/pull/31

**Comment by Yuki-Nagato** [comment]
最新版本还是不行，切换到deepin-wine5也不行。

**Comment by Yuki-Nagato** [comment]
找到了一个workaround：在鼠标移到图标的同时转动滚轮，有机会可以弹出信息列表。
