### ISSUE TITLE
kde5 manjaro 软件界面，文字缺失，没有文字显示

### ISSUE THREAD

**Issue by AshleyCry** [countstarlight/deepin-wine-qq-arch#24]
安装好后能够正常打开 但是界面上所有文字都缺失了 我用的是kde5的manjaro,没有报错信息
![image](https://user-images.githubusercontent.com/50860756/97873607-d865b500-1d52-11eb-9eb3-ee850a58ffce.png)

**Comment by sukanka** [comment]
我这样搞的，先切换成 deepinwine, 然后删除自带字体，链接 windows 字体（我自己复制了一份完整的 windows 字体放在 `/usr/share/fonts/Windows`下面），最后重启一次应该就好了
```
rm -rf ~/.deepinwine/Deepin-QQ/drive_c/windows/Fonts                   
sudo ln -s /usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc /usr/share/fonts/Windows
ln -s /usr/share/fonts/Windows ~/.deepinwine/Deepin-QQ/drive_c/windows/Fonts
reboot
```
目前一切正常

**Comment by AshleyCry** [comment]
> 我这样搞的，先切换成 deepinwine, 然后删除自带字体，链接 windows 字体（我自己复制了一份完整的 windows 字体放在 `/usr/share/fonts/Windows`下面），最后重启一次应该就好了
> 
> ```
> /opt/deepinwine/apps/Deepin-QQ/run.sh -d 
> rm -rf ~/.deepinwine/Deepin-QQ/drive_c/windows/Fonts                   
> sudo ln -s /usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc /usr/share/fonts/Windows
> ln -s /usr/share/fonts/Windows ~/.deepinwine/Deepin-QQ/drive_c/windows/Fonts
> reboot
> ```
> 
> 目前一切正常

我是重启了一下电脑自己就好了。。。
