### ISSUE TITLE
Deepin 社区因授权问题从镜像站移除了 deepin.com.qq.im 软件包

### ISSUE THREAD

**Issue by CyanoHao** [countstarlight/deepin-wine-qq-arch#27]
可能需要切换到 deepin 官方源。

```
==> Retrieving sources...
  -> Downloading deepin.com.qq.im_9.1.8deepin0_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
==> ERROR: Failure while downloading https://ftp.sjtu.edu.cn/deepin/pool/non-free/d/deepin.com.qq.im/deepin.com.qq.im_9.1.8deepin0_i386.deb
    Aborting...
```

Ref. 中科大镜像站公告 https://servers.ustclug.org/2020/10/deepin-changes/

**Comment by countstarlight** [comment]
感谢提醒，但目前 deepin官方源(https://packages.deepin.com) 的ssl证书可能有问题( https://github.com/countstarlight/deepin-wine-wechat-arch/issues/85#issuecomment-720981559 )，会导致下载出错，有其他源提供这个包吗？

**Comment by SamLukeYes** [comment]
> 感谢提醒，但目前 deepin官方源(https://packages.deepin.com) 的ssl证书可能有问题( [countstarlight/deepin-wine-wechat-arch#85 (comment)](https://github.com/countstarlight/deepin-wine-wechat-arch/issues/85#issuecomment-720981559) )，会导致下载出错，有其他源提供这个包吗？

https://cdn-package-store6.deepin.com/appstore/pool/appstore/c/com.qq.im.deepin/com.qq.im.deepin_9.3.2deepin14_i386.deb
这里有新版本，应该是基于 deepin-wine5 的

**Comment by zshnb** [comment]
要怎么修改build文件呢，我改了source提示md5sum校验不通过

**Comment by zx900930** [comment]
> 要怎么修改build文件呢，我改了source提示md5sum校验不通过

自己把那个deb下载下来，然后算好md5 填到build文件里的md5sums的第一项里去

**Comment by zshnb** [comment]
> > 要怎么修改build文件呢，我改了source提示md5sum校验不通过
> 
> 自己把那个deb下载下来，然后算好md5 填到build文件里的md5sums的第一项里去
> 例如这个qq的md5
> e12c4b26c791ca32cdc96e5441341148
> 还有那个PCQQ的md5
> 554b662419788aa893b5e342426f8548
> ![Screenshot_20201215_135032](https://user-images.githubusercontent.com/734749/102217371-c6903980-3edc-11eb-916f-62e50b6259b8.png)
> 改了可以成功跑过这一步，后面还会出现找不到~/.cache/yay/deepin-wine-qq/src/dpkgdir/usr/share/applications/deepin.com.qq.im.desktop
> 的错误，改动参考：
> 
> ```
> # Maintainer: Codist <countstarlight@gmail.com>
> 
> pkgname=deepin-wine-qq
> pkgver=9.4.0.27525
> qq_installer=PCQQ2020
> deepinqqver=9.3.2deepin14
> pkgrel=1
> pkgdesc="Tencent QQ (com.qq.im) on Deepin Wine For Archlinux"
> arch=("x86_64")
> url="http://im.qq.com/"
> license=('custom')
> depends=('p7zip' 'wine' 'wine-mono' 'wine-gecko' 'xorg-xwininfo' 'wqy-microhei' 'lib32-alsa-lib' 'lib32-alsa-plugins' 'lib32-libpulse' 'lib32-openal' 'lib32-mpg123' 'lib32-gnutls')
> conflicts=('deepin-qq-im' 'deepin.com.qq.im')
> install="deepin-wine-qq.install"
> _mirror="https://ftp.sjtu.edu.cn/deepin"
> source=("com.qq.im.deepin_9.3.2deepin14_i386.deb"
>   "PCQQ2020-9.4.0.27525.exe"
>   "run.sh"
>   "reg.patch")
> md5sums=('e12c4b26c791ca32cdc96e5441341148'
>   '554b662419788aa893b5e342426f8548'
>   '4c94025ae6183d855433fb4a68e483c1'
>   '62d7de16a69fd99bca881f801187ba13')
> 
> build() {
>   msg "Extracting DPKG package ..."
>   mkdir -p "${srcdir}/dpkgdir"
>   tar -xvf data.tar.xz -C "${srcdir}/dpkgdir"
>   sed "s/\(Categories.*$\)/\1Network;/" -i "${srcdir}/dpkgdir/opt/apps/com.qq.im.deepin/entries/applications/com.qq.im.deepin.desktop"
>   msg "Extracting Deepin Wine QQ archive ..."
>   7z x -aoa "${srcdir}/dpkgdir/opt/apps/com.qq.im.deepin/files/files.7z" -o"${srcdir}/deepinqqdir"
>   msg "Removing original outdated QQ directory ..."
>   rm -r "${srcdir}/deepinqqdir/drive_c/Program Files/Tencent/QQ"
>   msg "Patching reg files ..."
>   patch -p1 -d "${srcdir}/deepinqqdir/" < "${srcdir}/reg.patch"
>   msg "Creating font file link ..."
>   ln -sf "/usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc" "${srcdir}/deepinqqdir/drive_c/windows/Fonts/wqy-microhei.ttc"
>   msg "Repackaging app archive ..."
>   7z a -t7z -r "${srcdir}/files.7z" "${srcdir}/deepinqqdir/*"
> }
> 
> package() {
>   msg "Preparing icons ..."
>   install -d "${pkgdir}/usr/share"
>   cp -a ${srcdir}/dpkgdir/usr/share/* "${pkgdir}/usr/share/"
>   msg "Copying QQ to /opt/deepinwine/apps/Deepin-QQ ..."
>   install -d "${pkgdir}/opt/deepinwine/apps/Deepin-QQ"
>   install -m644 "${srcdir}/files.7z" "${pkgdir}/opt/deepinwine/apps/Deepin-QQ/"
>   install -m644 "${srcdir}/reg.patch" "${pkgdir}/opt/deepinwine/apps/Deepin-QQ/"
>   install -m755 "${srcdir}/run.sh" "${pkgdir}/opt/deepinwine/apps/Deepin-QQ/"
>   install -m644 "${srcdir}/${qq_installer}-${pkgver}.exe" "${pkgdir}/opt/deepinwine/apps/Deepin-QQ/"
> }
> ```
> 
> 还有那个注册表patch也得改，因为行数不一样了

谢谢大佬，原来要这么麻烦..希望官方早点能修好吧

**Comment by zx900930** [comment]
@zshnb 还有个简单的办法，就是你去https://gitee.com/wszqkzqk/deepin-wine-containers-for-ubuntu/raw/master/deepin.com.qq.im_9.1.8deepin0_i386.deb
下载好9.1.8的deb文件，放到你pacman的$Source文件夹里
然后pkgbuild里只需要改动
```
source=("deepin.com.qq.im_9.1.8deepin0_i386.deb"
  "PCQQ2020-9.4.0.27525.exe"
  "run.sh"
  "reg.patch")
md5sums=('d35bd4abfd1ac4c5e71c7fbc5282ccbd'
  '554b662419788aa893b5e342426f8548'
```
就可以正常完成安装，然后再参照github的readme和我更新的https://github.com/countstarlight/deepin-wine-qq-arch/issues/29切换成deepin-wine5(如果你的源还没有更新到deepin-wine5这一步可以不做)

**Comment by zshnb** [comment]
> @zshnb 还有个简单的办法，就是你去https://gitee.com/wszqkzqk/deepin-wine-containers-for-ubuntu/raw/master/deepin.com.qq.im_9.1.8deepin0_i386.deb
> 下载好9.1.8的deb文件，放到你pacman的$Source文件夹里
> 然后pkgbuild里只需要改动
> 
> ```
> source=("deepin.com.qq.im_9.1.8deepin0_i386.deb"
>   "PCQQ2020-9.4.0.27525.exe"
>   "run.sh"
>   "reg.patch")
> md5sums=('d35bd4abfd1ac4c5e71c7fbc5282ccbd'
>   '554b662419788aa893b5e342426f8548'
> ```
> 
> 就可以正常完成安装，然后再参照github的readme和我更新的 #29 切换成deepin-wine5(如果你的源还没有更新到deepin-wine5这一步可以不做)

好的，我去看看，谢谢你！

**Comment by Lapis-Apple** [comment]
我们是否应该Fork一份然后续更？作者似乎最近失踪了的样子..

**Comment by taotieren** [comment]
已修复 https://github.com/taotieren/deepin-wine-qq-arch/releases/tag/v9.4.1.27572-2

**Comment by countstarlight** [comment]
已更新：https://github.com/countstarlight/deepin-wine-qq-arch/commit/011ada8d48c55b4f5e50abadfb42c52d42dedde4
