### ISSUE TITLE
使用release下载的包直接安装，qq安装好后无法运行

### ISSUE THREAD

**Issue by HO-COOH** [countstarlight/deepin-wine-qq-arch#30]
如图
![image](https://user-images.githubusercontent.com/42881734/102774390-81db2700-4350-11eb-98a5-6caf9fd48335.png)

**Comment by taotieren** [comment]
已修复 
https://github.com/countstarlight/deepin-wine-qq-arch/pull/31

**Comment by HO-COOH** [comment]
感谢大佬的维护
