### ISSUE TITLE
使用多彩气泡时聊天输入框的字就会变成框框

### ISSUE THREAD

**Issue by HO-COOH** [countstarlight/deepin-wine-qq-arch#32]
![image](https://user-images.githubusercontent.com/42881734/103137738-2e8b1080-4691-11eb-907f-09c482ebd547.png)
只是聊天输入框的字会变框框，聊天信息都可以正常显示，可能还是有字体缺失问题

**Comment by HO-COOH** [comment]
动态也有问题
![image](https://user-images.githubusercontent.com/42881734/103153708-1500cc00-4758-11eb-9b16-300766de7976.png)

**Comment by countstarlight** [comment]
升级到 `v9.4.2.27655-1` ，再清除一下之前的安装文件试试：
```bash
rm -rf ~/.deepinwine/Deepin-QQ
```

**Comment by HO-COOH** [comment]
9.4.2解决了

**Comment by zx900930** [comment]
这个问题在最新版也存在啊，并没有解决。
![Screenshot_20210105_102350](https://user-images.githubusercontent.com/734749/103629154-450e5300-4f40-11eb-983e-ee666ffcbb9c.png)
而且点空间动态会直接崩溃
![Screenshot_20210105_102629](https://user-images.githubusercontent.com/734749/103629384-84d53a80-4f40-11eb-8a06-e199922c7ac1.png)

**Comment by countstarlight** [comment]
`v9.4.2.27658-1` 已经修复了这个问题，建议参照 [自动切换](https://github.com/countstarlight/deepin-wine-qq-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90) 切换到 `deepin-wine`
