### ISSUE TITLE
表情页极卡

### ISSUE THREAD

**Issue by FlyInWind1** [countstarlight/deepin-wine-qq-arch#34]
![20201226_150407](https://user-images.githubusercontent.com/29172747/103147033-d127ba00-478b-11eb-9a0b-63c06bb0ffc2.png)
打开表情页面，点一下半天动不了

**Comment by countstarlight** [comment]
`v9.4.2.27658-1` 已经修复了这个问题，建议参照 [自动切换](https://github.com/countstarlight/deepin-wine-qq-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90) 切换到 `deepin-wine`
