### ISSUE TITLE
除了与好友聊天之外点其他都会崩溃

### ISSUE THREAD

**Issue by qwe7410** [countstarlight/deepin-wine-qq-arch#40]
例如上线会弹一个腾讯网的消息，点了就会卡死崩溃，进设置同样.

**Comment by qwe7410** [comment]
> 例如上线会弹一个腾讯网的消息，点了就会卡死崩溃，进设置同样.

容器环境改成xp即可

**Comment by HO-COOH** [comment]
+1，打开动态100%卡死

**Comment by countstarlight** [comment]
`v9.4.2.27658-1` 已经修复了这个问题，建议参照 [自动切换](https://github.com/countstarlight/deepin-wine-qq-arch#%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E6%8E%A8%E8%8D%90) 切换到 `deepin-wine`
