### ISSUE TITLE
右键菜单栏功能无法使用

### ISSUE THREAD

**Issue by Ca1seMonika** [countstarlight/deepin-wine-qq-arch#43]
如 选中文字后右键的复制粘贴等功能， 头像旁切换在线状态功能

**Comment by countstarlight** [comment]
在archlinux + kde，`deepin-wine 5.0.16-1` 上不能复现这个问题

**Comment by Ca1seMonika** [comment]
> 在archlinux + kde，`deepin-wine 5.0.16-1` 上不能复现这个问题

这个问题是在xfce4上发现的

**Comment by Ca1seMonika** [comment]
> > 在archlinux + kde，`deepin-wine 5.0.16-1` 上不能复现这个问题
> 
> 这个问题是在xfce4上发现的

且也是在deepin-wine5中
