### ISSUE TITLE
最小化到托盘的问题

### ISSUE THREAD

**Issue by logTXT** [countstarlight/deepin-wine-qq-arch#5]
主页面最小化之后，在托盘里面找不到QQ的图标，也没办法重其他地方唤醒，只能杀掉qq的进程之后再重新登录，有没有方便的解决办法？

**Comment by countstarlight** [comment]
抱歉回复晚了。是什么系统，桌面环境是什么？

**Comment by JarvisLi** [comment]
manjaro 18.04，deepin桌面，我的最小化之后有显示托盘图标，但点击无反应

**Comment by logTXT** [comment]
screenfecth的结果：
 ██████████████████  ████████     logtxt@log-pc
 ██████████████████  ████████     OS: Manjaro 18.0.4 Illyria
 ██████████████████  ████████     Kernel: x86_64 Linux 5.0.9-2-MANJARO
 ██████████████████  ████████     Uptime: 45m
 ████████                           ████████     Packages: 1282
 ████████  ████████  ████████     Shell: zsh 5.7.1
 ████████  ████████  ████████     Resolution: 1366x768
 ████████  ████████  ████████     DE: KDE 5.57.0 / Plasma 5.15.4
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Breath [GTK2/3]
 ████████  ████████  ████████     Icon Theme: maia
 ████████  ████████  ████████     Font: Noto Sans Regular
 ████████  ████████  ████████     CPU: Intel Celeron N2840 @ 2x 2.5823GHz
 ████████  ████████  ████████     GPU: Mesa DRI Intel(R) Bay Trail
                                  RAM: 2589MiB / 3826MiB 
程序运行起来就没有托盘图标，最小化之后就不知道去哪里了，只能杀掉进程重开

**Comment by countstarlight** [comment]
> manjaro 18.04，deepin桌面，我的最小化之后有显示托盘图标，但点击无反应

deepin-dock不支持：https://github.com/linuxdeepin/developer-center/issues/781

**Comment by countstarlight** [comment]
@logTXT 在archlinux+kde上没有这个问题，我稍候安装一下manjaro+kde，尝试复现这个问题

**Comment by huming2207** [comment]
最新版Manjaro+Deepin（2019/5/30）也有这个问题，点了没反应

**Comment by logTXT** [comment]
换成 win10+Arch in WSL 了🤣 ，这个issue先关了吧，有人有需求再开
