### ISSUE TITLE
缺失help_archive.md5sum导致重复解压helper_archive.7z

### ISSUE THREAD

**Issue by muwuren** [countstarlight/deepin-wine-qq-arch#54]
非常感谢作者们的努力让我可以在manjaro linux上完美运行deepin-wine版的qq。
我发现一处问题，在#48中，@AsterisMono提到每次使用/opt/apps/com.qq.im.deepin/files/run.sh脚本启动qq时，会导致~/.deepinwine/deepin-wine-helper目录的覆盖，即重新解压/opt/apps/com.qq.im.deepin/files/helper_archive.7z文件。
这是由于run.sh中，第22行，会对archive_version和dest_version值进行对比，两者均为空值。之后判断dest_version为空后，进行解压。由于这两个变量的值实际都来自run.sh的第99行的函数调用的第二个参数，即/opt/apps/com.qq.im.deepin/files/helper_archive.md5sum。
![图片](https://user-images.githubusercontent.com/32675834/127347142-600e8495-4012-4708-876b-ec30b61a9794.png)
应该补充helper_archive.md5sum这个文件，避免每次启动qq对文件的重复解压。
PKGBUILD中添加`md5sum "${srcdir}/help_archive.7z" | awk '{ print $1 }' > "${pkgdir}/opt/apps/${debpkgname}/files/help_archive.md5sum"`。
修复之后在#48中，@AsterisMono的方法可以直接修改家目录下文件映射即可。

**Comment by countstarlight** [comment]
感谢帮助
* 应该是deepin打包时遗漏了 `help_archive.md5sum`，deepin打包的微信 `com.qq.weixin.deepin` 中是有这个文件的。
* 虽然文件后缀是 `.md5sum`，但 deepin 在 `com.qq.weixin.deepin`(版本: `3.2.1.154deepin8`)中的 `help_archive.md5sum` 文件内容是 `5.1.19-1`，所以直接计算 `help_archive.7z` 的md5值在进行版本比较时可能会有问题。
* 因为 `com.qq.weixin.deepin`(版本: `3.2.1.154deepin8`) 的 `helper_archive.7z` 中文件日期更新，所以暂定 qq 的 `help_archive.md5sum` 文件内容为 `5.1.13-1`
