### ISSUE TITLE
极其严重的卡死

### ISSUE THREAD

**Issue by floatingrain** [countstarlight/deepin-wine-qq-arch#6]
输入帐号密码正常，点击登录后开始严重卡顿，动画流畅但窗口无反应，CPU占用率持续10%。稍等几分钟后登录成功显示主界面，此时完全卡死，点击窗口不会有任何反馈。

**Comment by FlyInWind1** [comment]
最好的办法还是出个几十亿，让腾讯专门维护一个linux版

**Comment by countstarlight** [comment]
参照 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/15#issuecomment-515455845 换用 `deepin-wine` 试试
