### ISSUE TITLE
使用ibus-rime时无法输入中文

### ISSUE THREAD

**Issue by wold9168** [countstarlight/deepin-wine-qq-arch#79]
使用ibus-rime在deepin-wine-qq的聊天框内进行输入时，输入法没有反应。

`~/.xprofile`文件内容如下：
```
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=ibus
export XIM=ibus
ibus-daemon -x -d
```

_这是我第一次在GitHub上就程序问题递交issue，盼好。_

**Comment by vufa** [comment]
Hi，我没有使用ibus，或许你可以试试参照[arch wiki](https://wiki.archlinux.org/title/IBus_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))修改`~/.profile`:
```diff
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
-export XMODIFIERS=ibus
+export XMODIFIERS=@im=ibus
export XIM=ibus
ibus-daemon -x -d
```
并重启系统，还可能和你使用的桌面环境有关

**Comment by wold9168** [comment]
很高兴我的问题得到了解决。
当我将`~/.xprofile`中的内容改为如您所述的那样并重启以后，问题解决了。
我的`~/.profile`文件中的内容自一开始便是照搬wiki的，也就是说其内容和您贴上来的代码片段是一样的。

顺带一提，我的桌面环境是Xfce 4
