### ISSUE TITLE
安装过程中，提示PCQQ2019.exe验证失败

### ISSUE THREAD

**Issue by alexanderhawl** [countstarlight/deepin-wine-qq-arch#8]
正在验证 source 文件，使用md5sums...
    deepin.com.qq.im_8.9.19983deepin23_i386.deb ... 通过
    PCQQ2019.exe ... 失败
    run.sh ... 通过
    reg.patch ... 通过
==> 错误： 一个或多个文件没有通过有效性检查！

**Comment by countstarlight** [comment]
还没有办法让新版的qq运行起来，可以[用安装包安装](https://github.com/countstarlight/deepin-wine-qq-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

**Comment by countstarlight** [comment]
deepin-wine-qq 9.1.8.26211-2 已经发布
