### ISSUE TITLE
打开好友动态会崩溃

### ISSUE THREAD

**Issue by mill413** [countstarlight/deepin-wine-qq-arch#80]
不管是聊天界面还是主面板，一点击好友动态都会直接卡死然后崩溃

**Comment by Onetopabove** [comment]
https://github.com/vufa/deepin-wine-qq-arch#%E4%B8%8D%E8%83%BD%E5%90%AF%E5%8A%A8%E5%8D%A1%E6%AD%BB%E5%8D%A1%E9%A1%BF%E9%97%AE%E9%A2%98
试试这个
