### ISSUE TITLE
不能通过aur来安装

### ISSUE THREAD

**Issue by xiguayuyichao** [countstarlight/deepin-wine-qq-arch#87]
[xiguayuyichao@xigua-archlinux ~]$ yay -S deepin-wine-qq
 -> 找不到所有需要的包:
        deepin-udis86 (被这些包需要: deepin-wine-qq -> deepin-wine5 -> deepin-wine5-i386)
[xiguayuyichao@xigua-archlinux ~]$

**Comment by rainyNighti** [comment]
您好，你解决了吗，我也遇到了这个问题，TIM，QQ都无法安装

**Comment by rainyNighti** [comment]
我解决了，先安装这个依赖的代替即可：yay -Sy lib32-udis86-git
