### ISSUE TITLE
wine下中文字体无法输入,有解决办法吗

### ISSUE THREAD

**Issue by L-Ryland** [countstarlight/deepin-wine-qq-arch#9]
Arch Linux, 桌面环境KDE, 输入法fcitx-sogoupinyin, 只能输入英文

**Comment by countstarlight** [comment]
降级wine到4.16 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/31

**Comment by L-Ryland** [comment]
谢谢大佬,问题已解决!
